[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	lemmingdev/ESP32-BLE-Gamepad @ ^0.7.4
	h2zero/NimBLE-Arduino @ ^2.0.0

build_flags = 
	-D USE_NIMBLE
	-include Arduino.h
